site_name: Driverless Kart Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Hardware:
      - Battery: hardware/battery/index.md
      - Camera: hardware/camera/index.md
      - Computer: hardware/computer/index.md
      - Motor: hardware/motor/index.md
      - Steering:
          - Overview: hardware/steering/index.md
          - H-bridge: hardware/steering/h-bridge.md
          - Steering Angle Sensor: hardware/steering/sensor/index.md
      
      # - Blue Pill: hardware/blue-pill/index.md # commented out because it is not used anymore
      - ESP32: hardware/esp32/index.md
  - Electrical: electrical/index.md
  - Assembly: assembly/index.md
  - Pneumatics: pneumatics/index.md
  - Hydraulics: hydraulics/index.md
  - Software: software/index.md
  - FAQ: faq.md
  - Contact: contact.md
repo_url: https://github.com/um-driverless/kart_docs
edit_uri: edit/main/docs/
plugins:
  - search
  - exporter:
      enabled: !ENV [EXPORT_PDF, false] # ← only runs when EXPORT_PDF=true
      formats:
        pdf:
          pages:
            enabled: false # keep only the book-size PDF
          aggregator:
            enabled: true
            output: kart-documentation.pdf
